# Generated by Django 5.1 on 2024-10-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0010_alter_cursos_años'),
    ]

    operations = [
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Año', models.CharField(choices=[('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('monto_matricula', models.FloatField()),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
            ],
        ),
    ]
