# Generated by Django 5.1 on 2024-10-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'matricula', 'verbose_name_plural': 'matriculas'},
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matriculas',
        ),
    ]
