# Generated by Django 5.1 on 2024-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_pagomatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomatricula',
            name='cheque',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='efectivo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='pagare',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='transferencia',
            field=models.FloatField(null=True),
        ),
    ]
