# Generated by Django 5.1 on 2024-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0004_alter_pagomatricula_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomatricula',
            name='cheque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='efectivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='pagare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagomatricula',
            name='transferencia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
