# Generated by Django 5.1 on 2024-10-01 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0005_alter_pagomatricula_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomatricula',
            name='fecha_pago_matricula',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
