# Generated by Django 5.1 on 2024-10-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_remove_cuotas_fecha_hora_cuotas_anticipado_and_more'),
        ('contable', '0006_pagomatricula_fecha_pago_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagocuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.FloatField(blank=True, null=True)),
                ('transferencia', models.FloatField(blank=True, null=True)),
                ('cheque', models.FloatField(blank=True, null=True)),
                ('pagare', models.FloatField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cuotas')),
            ],
            options={
                'verbose_name': 'pagocuota',
                'verbose_name_plural': 'pagocuotas',
                'db_table': 'pagocuotas',
            },
        ),
    ]
