# Generated by Django 5.1 on 2024-10-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0008_alter_matricula_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='descuento',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
