# Generated by Django 5.1 on 2024-10-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0009_pagocuota_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('tipo_ingreso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'egreso',
                'verbose_name_plural': 'egresos',
                'db_table': 'egresos',
            },
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('tipo_ingreso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
                'db_table': 'ingresos',
            },
        ),
    ]
