# Generated by Django 5.1 on 2024-11-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_alter_cuotas_monto_cuota'),
        ('contable', '0010_egreso_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_hora_del_pago', models.DateField(blank=True, default=None, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cuotas')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.matricula')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tutores')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibos',
            },
        ),
    ]
