# Generated by Django 5.1 on 2024-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0011_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomatricula',
            name='Pagado',
            field=models.BooleanField(default=False),
        ),
    ]
