# Generated by Django 5.1 on 2024-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0012_pagomatricula_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
