# Generated by Django 5.1 on 2024-11-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_alter_cursos_nivels_alter_cursos_años'),
        ('contable', '0014_pagomatricula_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.cuotas'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contable.matricula'),
        ),
    ]
