# Generated by Django 5.1 on 2024-11-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_alter_cursos_nivels_alter_cursos_años'),
        ('contable', '0015_alter_recibo_cuota_alter_recibo_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.tutores'),
        ),
    ]
