# Generated by Django 5.1 on 2024-11-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0016_alter_recibo_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
