# Generated by Django 5.1 on 2024-11-14 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0017_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contable.egreso'),
        ),
        migrations.AddField(
            model_name='extras',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contable.ingresos'),
        ),
    ]
