# Generated by Django 5.1 on 2024-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('Domicilio_Personal', models.CharField(max_length=255)),
                ('Domicilio_Laboral', models.CharField(max_length=255)),
                ('Celular', models.CharField(max_length=255)),
                ('Ocupacion', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Vive', models.CharField(max_length=255)),
                ('Responsable_de_pago', models.BooleanField()),
                ('Parentezco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutores',
                'db_table': 'tutores',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Familia', models.CharField(default=None, max_length=255)),
                ('Tutores', models.ManyToManyField(to='academico.tutores')),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'db_table': 'familias',
            },
        ),
    ]
