# Generated by Django 5.1 on 2024-09-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
                'db_table': 'Casas',
            },
        ),
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'Colegios',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('años', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo')], default=1, max_length=1)),
                ('Nivels', models.CharField(choices=[('1', 'Inicial'), ('2', 'Primario'), ('3', 'Secundario')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisiones',
                'db_table': 'Divisiones',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=255)),
                ('Nombres', models.CharField(max_length=255)),
                ('CUIL', models.CharField(max_length=255)),
                ('Tel', models.CharField(max_length=255)),
                ('F_Nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Familia', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'db_table': 'familias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Localidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Lugar_Nacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Lugar de Nacimiento',
                'verbose_name_plural': 'Lugar de Nacimientos',
                'db_table': 'Lugar de Nacimiento',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nacionalidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel de Docente',
                'verbose_name_plural': 'Nivel de Docentes',
                'db_table': 'Nivel de Docentes',
            },
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Parentezco',
                'verbose_name_plural': 'Parentezcos',
                'db_table': 'Parentezcos',
            },
        ),
        migrations.CreateModel(
            name='Titulos_Profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominación', models.CharField(max_length=255)),
                ('Observación', models.TextField()),
            ],
            options={
                'verbose_name': 'Titulos Profesional',
                'verbose_name_plural': 'Titulos Profesionales',
                'db_table': 'Titulos Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'db_table': 'Valores',
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baja_Alumno', models.BooleanField()),
                ('Apellidos', models.CharField(max_length=255)),
                ('Nombres', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('Edad', models.IntegerField()),
                ('Fecha_Nacimiento', models.DateField()),
                ('Domicilio', models.CharField(max_length=255)),
                ('Email_Institucional', models.EmailField(max_length=254)),
                ('Email_Personal', models.EmailField(max_length=254)),
                ('Escuela_Procedencia', models.CharField(max_length=255)),
                ('Enfermedades', models.CharField(max_length=255)),
                ('Toma_Medicamentos', models.CharField(max_length=255)),
                ('Telefono_Urgencia', models.CharField(max_length=255)),
                ('Sexo', models.CharField(choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1)),
                ('Casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.casas')),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.colegios')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cursos')),
                ('Familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.familia')),
                ('Localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.localidad')),
                ('Lugar_Nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.lugar_nacimiento')),
                ('Nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nacionalidad')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes_año', models.DateField(default=None)),
                ('Fecha_hora', models.DateTimeField()),
                ('Pagado', models.BooleanField(default=False)),
                ('Alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'Cuotas',
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.division'),
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominación', models.CharField(max_length=255)),
                ('Docente_Titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docentes')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='Materias',
            field=models.ManyToManyField(to='academico.materias'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='Nivel_Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nivel_docente'),
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_en_clases', models.CharField(blank=True, max_length=255)),
                ('tp_individual_1', models.CharField(blank=True, max_length=255)),
                ('tp_individual_2', models.CharField(blank=True, max_length=255)),
                ('leccion_oral_individual', models.CharField(blank=True, max_length=255)),
                ('evaluacion_escrita', models.CharField(blank=True, max_length=255)),
                ('exposicion_grupal_nota_grupal', models.CharField(blank=True, max_length=255)),
                ('exposicion_grupal_nota_individual', models.CharField(blank=True, max_length=255)),
                ('exposicion_grupal_soporte_presentacion', models.CharField(blank=True, max_length=255)),
                ('laboratorio_taller', models.CharField(blank=True, max_length=255)),
                ('carpeta', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('conducta', models.CharField(blank=True, max_length=255)),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
                ('materias', models.ManyToManyField(to='academico.materias')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'db_table': 'notas',
            },
        ),
        migrations.AddField(
            model_name='docentes',
            name='Titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.titulos_profesionales'),
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('Domicilio_Personal', models.CharField(max_length=255)),
                ('Domicilio_Laboral', models.CharField(max_length=255)),
                ('Celular', models.CharField(max_length=255)),
                ('Ocupacion', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Vive', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('Responsable_de_pago', models.BooleanField()),
                ('Parentezco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.parentezco')),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutores',
                'db_table': 'tutores',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='Tutores',
            field=models.ManyToManyField(to='academico.tutores'),
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
                ('Valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.valor')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencias',
            },
        ),
    ]
