# Generated by Django 5.1 on 2024-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_delete_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Familia', models.CharField(default=None, max_length=255)),
                ('Tutores', models.ManyToManyField(to='academico.tutores')),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'db_table': 'familias',
            },
        ),
    ]
