# Generated by Django 5.1 on 2024-09-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_casas_colegios_localidad_lugar_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Familia', models.IntegerField()),
                ('Tutor', models.IntegerField()),
                ('Asistencia', models.BooleanField()),
                ('Baja_Alumno', models.BooleanField()),
                ('Niveles_Alumno', models.IntegerField()),
                ('Apellidos', models.CharField(max_length=255)),
                ('Nombres', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('Edad', models.IntegerField()),
                ('Fecha_Nacimiento', models.DateField()),
                ('Domicilio', models.CharField(max_length=255)),
                ('Email_Institucional', models.EmailField(max_length=254)),
                ('Email_Personal', models.EmailField(max_length=254)),
                ('Escuela_Procedencia', models.CharField(max_length=255)),
                ('Enfermedades', models.CharField(max_length=255)),
                ('Toma_Medicamentos', models.CharField(max_length=255)),
                ('Telefono_Urgencia', models.CharField(max_length=255)),
                ('Sexo', models.CharField(max_length=255)),
                ('Casas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.casas')),
                ('Colegios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.colegios')),
                ('Localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.localidad')),
                ('Lugar_Nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.lugar_nacimiento')),
                ('Nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nacionalidad')),
            ],
        ),
    ]
