# Generated by Django 5.1 on 2024-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_notas_alumnos_remove_notas_materias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='Materias',
            field=models.ManyToManyField(related_name='cursos', to='academico.materias'),
        ),
    ]
