# Generated by Django 5.1 on 2024-09-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField()),
                ('Alumno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asistencias'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='Valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.valor'),
        ),
    ]
