# Generated by Django 5.1 on 2024-09-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_cursos_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='academico.cursos'),
        ),
    ]
