# Generated by Django 5.1 on 2024-09-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_asistencias_valor_alter_alumnos_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_hora', models.DateTimeField()),
                ('Estado', models.CharField(max_length=255)),
                ('Alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
            ],
        ),
    ]
