# Generated by Django 5.1 on 2024-09-02 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_cuotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Año', models.IntegerField()),
                ('Tipo', models.CharField(max_length=255)),
                ('Observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(max_length=255)),
                ('Observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materias', models.IntegerField()),
                ('Año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.año')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.division')),
                ('Nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nivel')),
            ],
        ),
    ]
