# Generated by Django 5.1 on 2024-09-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_casas_options_alter_colegios_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Parentezco',
                'verbose_name_plural': 'Parentezcos',
                'db_table': 'Parentezcos',
            },
        ),
        migrations.AlterField(
            model_name='tutores',
            name='Parentezco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.parentezco'),
        ),
    ]
