# Generated by Django 5.1 on 2024-10-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_alter_cursos_años'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas',
            name='Fecha_hora',
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Anticipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Anticipado_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Extraordinario',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Fecha_hora_del_pago',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Monto_cuota',
            field=models.FloatField(default=200000),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academico.tutores'),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='Mes_año',
            field=models.IntegerField(default=None),
        ),
    ]
