# Generated by Django 5.1 on 2024-09-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_parentezco_alter_tutores_parentezco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='Casas',
            new_name='Casa',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='Colegios',
            new_name='Colegio',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Asistencia',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Tutor',
        ),
        migrations.RemoveField(
            model_name='cuotas',
            name='Estado',
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Mes_año',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.familia'),
        ),
    ]
