# Generated by Django 5.1 on 2024-10-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_remove_cuotas_fecha_hora_cuotas_anticipado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mes_año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mes', models.IntegerField(default=None)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'mes_año',
                'verbose_name_plural': 'mes_años',
                'db_table': 'mes_años',
            },
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='Mes_año',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.mes_año'),
        ),
    ]
