# Generated by Django 5.1 on 2024-09-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_rename_casas_alumnos_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='Niveles_Alumno',
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='Alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos'),
        ),
    ]
