# Generated by Django 5.1 on 2024-09-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_remove_alumnos_niveles_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valor',
            name='Tipo',
        ),
    ]
