# Generated by Django 5.1 on 2024-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_mes_año_alter_cuotas_mes_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='Extraordinario',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
