# Generated by Django 5.1 on 2024-09-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_remove_valor_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='asistencias',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='año',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='cuotas',
            options={'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisiones'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='lugar_nacimiento',
            options={'verbose_name': 'Lugar_Nacimiento', 'verbose_name_plural': 'Lugar_Nacimientos'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='valor',
            options={'verbose_name': 'Valor', 'verbose_name_plural': 'Valores'},
        ),
        migrations.AlterModelTable(
            name='alumnos',
            table='Alumnos',
        ),
        migrations.AlterModelTable(
            name='asistencias',
            table='Asistencias',
        ),
        migrations.AlterModelTable(
            name='año',
            table='Años',
        ),
        migrations.AlterModelTable(
            name='cuotas',
            table='Cuotas',
        ),
        migrations.AlterModelTable(
            name='division',
            table='Divisiones',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='Localidades',
        ),
        migrations.AlterModelTable(
            name='lugar_nacimiento',
            table='Lugar_Nacimiento',
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidades',
        ),
        migrations.AlterModelTable(
            name='valor',
            table='Valores',
        ),
    ]
