# Generated by Django 5.1 on 2024-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_alter_cuotas_extraordinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='Mes_año',
            field=models.CharField(max_length=4),
        ),
    ]
