# Generated by Django 5.1 on 2024-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_cuotas_mes_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas',
            name='Mes_año',
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Año',
            field=models.CharField(default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='Mes',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
