# Generated by Django 5.1 on 2024-09-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_alumnos_options_alter_asistencias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='Niveles',
        ),
    ]
