# Generated by Django 5.1 on 2024-09-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_nivel_options_alter_nivel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar_nacimiento',
            options={'verbose_name': 'Lugar de Nacimiento', 'verbose_name_plural': 'Lugar de Nacimientos'},
        ),
        migrations.AlterModelTable(
            name='lugar_nacimiento',
            table='Lugar de Nacimiento',
        ),
    ]
