# Generated by Django 5.1 on 2024-10-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_remove_cuotas_mes_año_cuotas_año_cuotas_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='Fecha_hora_del_pago',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
