# Generated by Django 5.1 on 2024-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_cuotas_fecha_hora_del_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='Monto_cuota',
            field=models.FloatField(default=None),
        ),
    ]
