# Generated by Django 5.1 on 2024-11-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_alter_cuotas_monto_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Años',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Año', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'db_table': 'Años',
            },
        ),
    ]
