# Generated by Django 5.1 on 2024-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_alter_cursos_options_alter_cursos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominación', models.CharField(max_length=255)),
                ('Profesor_Titular', models.IntegerField()),
                ('Profesor_Interino', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Materias',
        ),
        migrations.AddField(
            model_name='cursos',
            name='Materias',
            field=models.ManyToManyField(to='academico.materias'),
        ),
    ]
