# Generated by Django 5.1 on 2024-11-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_años'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='Nivels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nivel'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='años',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.años'),
        ),
    ]
