# Generated by Django 5.1 on 2024-09-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_materias_remove_cursos_materias_cursos_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel de Docente',
                'verbose_name_plural': 'Nivel de Docentes',
                'db_table': 'Nivel de Docentes',
            },
        ),
        migrations.CreateModel(
            name='Titulos_Profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominación', models.CharField(max_length=255)),
                ('Observación', models.TextField()),
            ],
            options={
                'verbose_name': 'Titulos Profesional',
                'verbose_name_plural': 'Titulos Profesionales',
                'db_table': 'Titulos Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=255)),
                ('Nombres', models.CharField(max_length=255)),
                ('CUIL', models.CharField(max_length=255)),
                ('Tel', models.CharField(max_length=255)),
                ('F_Nacimiento', models.DateField()),
                ('Nivel_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nivel_docente')),
                ('Titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.titulos_profesionales')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docentes',
            },
        ),
    ]
