# Generated by Django 5.1 on 2024-09-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_nivel_docente_titulos_profesionales_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='año',
            name='Observacion',
        ),
        migrations.RemoveField(
            model_name='division',
            name='Observacion',
        ),
    ]
