# Generated by Django 5.1 on 2024-09-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_remove_año_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='Profesor_Interino',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='Profesor_Titular',
        ),
        migrations.AddField(
            model_name='materias',
            name='Docente_Titular',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academico.docentes'),
        ),
    ]
