# Generated by Django 5.1 on 2024-09-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_alter_materias_docente_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='Docente_Titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docentes'),
        ),
    ]
