# Generated by Django 5.1 on 2024-09-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_alter_materias_docente_titular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='Materias',
        ),
        migrations.DeleteModel(
            name='Materias',
        ),
    ]
