# Generated by Django 5.1 on 2024-09-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_remove_cursos_materias_delete_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominación', models.CharField(max_length=255)),
                ('Docente_Titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docentes')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
    ]
