# Generated by Django 5.1 on 2024-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Materias',
            field=models.ManyToManyField(to='academico.materias'),
        ),
    ]
