# Generated by Django 5.1 on 2024-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0029_alter_alumnos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutores',
            name='Vive',
            field=models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1),
        ),
    ]
