# Generated by Django 5.1 on 2024-09-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0031_alter_tutores_vive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='Año',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Nivel',
        ),
        migrations.AddField(
            model_name='cursos',
            name='Nivels',
            field=models.CharField(choices=[('1', 'Inicial'), ('2', 'Primario'), ('3', 'Secundario')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='cursos',
            name='años',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='Año',
        ),
    ]
