# Generated by Django 5.1 on 2024-09-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_remove_cursos_año_remove_cursos_nivel_cursos_nivels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_en_clases', models.CharField(max_length=255)),
                ('tp_individual_1', models.CharField(max_length=255)),
                ('tp_individual_2', models.CharField(max_length=255)),
                ('leccion_oral_individual', models.CharField(max_length=255)),
                ('evaluacion_escrita', models.CharField(max_length=255)),
                ('exposicion_grupal_nota_grupal', models.CharField(max_length=255)),
                ('exposicion_grupal_nota_individual', models.CharField(max_length=255)),
                ('exposicion_grupal_soporte_presentacion', models.CharField(max_length=255)),
                ('laboratorio_taller', models.CharField(max_length=255)),
                ('carpeta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('conducta', models.CharField(max_length=255)),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos')),
                ('materias', models.ManyToManyField(to='academico.materias')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'db_table': 'notas',
            },
        ),
    ]
